/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bi_kernelImpl */

#ifndef _Included_com_bi_kernelImpl
#define _Included_com_bi_kernelImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bi_kernelImpl
 * Method:    main
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bi_kernelImpl_main
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
